[package]
name = "async-sequential"
version = "0.7.4"
edition = "2024"
authors = ["OkaYu"]
license = "MIT OR Apache-2.0"
description = "Running tasks sequentially on shared mutable state."
keywords = ["async", "executor", "sequential", "state", "tokio"]
repository = "https://github.com/aiueo13/async-sequential"
readme = "README.md"

[dependencies]
tokio = { version = "1", default-features = false, features = [
    # For `tokio::task::spawn` and `tokio::task::spawn_blocking`
    "rt",
    # For `tokio::sync::oneshot`
    "sync"
] }

[dev-dependencies]
tokio = { version = "1", features = ["sync", "rt", "macros", "time", "rt-multi-thread"] }
tokio-test = "0.4"
criterion = "0.8"

[[bench]]
name = "async_task_on_multi_thread_runtime"
harness = false

[[bench]]
name = "async_task_on_single_thread_runtime"
harness = false

[[bench]]
name = "blocking_task_on_multi_thread_runtime"
harness = false

[[bench]]
name = "blocking_task_on_single_thread_runtime"
harness = false