[package]
name = "async-sequential"
version = "0.10.0"
edition = "2024"
authors = ["OkaYu"]
license = "MIT OR Apache-2.0"
description = "Running tasks sequentially on shared mutable state."
keywords = ["async", "queue", "sequential", "state", "task"]
repository = "https://github.com/aiueo13/async-sequential"
readme = "README.md"

[dependencies]
tokio = { version = "1", features = [
    # To use `tokio::task`
    "rt",
    # To use `tokio::sync`
    "sync"
] }

[dev-dependencies]
tokio = { version = "1", features = ["sync", "rt", "macros", "time", "rt-multi-thread"] }
tokio-test = "0.4"